config/routes.rb
Rails.application.routes.draw do

  get 'bug_report/show'

  namespace :admin do
  get 'bug_reports/index'
  end

  namespace :admin do 
    get 'dashboard/dashboard', to: 'dashboard#dashboard', as: :dashboard
    # get 'dashboard/activity_feed', to: 'dashboard#activity_feed', as: :activity_feed
    patch 'companies/:id/update_button', to: 'companies#update_button', as: :update_button_for_company
    patch 'companies/:id/contact_company', to: 'companies#contact_company', as: :contact_company
    patch 'companies/:id/allow_changes_to_company', to: 'companies#allow_changes_to_company', as: :allow_changes_to_company
    patch 'companies/:id/deal_with_company', to: 'companies#deal_with_company', as: :deal_with_company

    patch 'job_descriptions/:id/update_button', to: 'job_descriptions#update_button', as: :update_button_for_jd
    patch 'job_descriptions/:id/allow_changes_to_jd', to: 'job_descriptions#allow_changes_to_jd', as: :allow_changes_to_jd
    patch 'applicants/:id/allow_changes_to_applicant', to: 'applicants#allow_changes_to_applicant', as: :allow_changes_to_applicant

    patch 'qualifications/:id/allow_changes_to_qualification', to: 'qualifications#allow_changes_to_qualification', as: :allow_changes_to_qualification
    patch 'required_experiences/:id/allow_changes_to_req_exp', to: 'required_experiences#allow_changes_to_req_exp', as: :allow_changes_to_req_exp
    patch 'requirements/:id/allow_changes_to_requirement', to: 'requirements#allow_changes_to_requirement', as: :allow_changes_to_requirement

    patch 'admin_users/:id/update_button', to: 'admin_users#update_button', as: :update_button_for_admin
    get 'activity_feed/index', to: 'activity_feed#index', as: :activity_feed
    get 'activity_feed/show', to: 'activity_feed#show', as: :show_activity
    patch 'messages/:id/send_message', to: 'messages#send_message', as: :send_message
    patch  'messages/:id/archive_message', to: 'messages#archive_message', as: :archive_message
    patch  'messages/:id/unarchive_message', to: 'messages#unarchive_message', as: :unarchive_message
    patch 'applicants/:id/update_salary', to: 'applicants#update_salary', as: :update_salary
    patch 'applicants/:id/update_button', to: 'applicants#update_button', as: :update_button_for_applicants
    get 'applicants/all_applicants', to: 'applicants#all_applicants', as: :manage_all_applicants
    patch 'users/:id/approve', to: 'users#approve', as: :approve_user
    patch 'users/:id/disapprove', to: 'users#disapprove', as: :disapprove_user
    patch 'applicants/:id/shortlist', to: 'applicants#shortlist', as: :shortlist_applicant
    patch 'applicants/:id/interviewing', to: 'applicants#interviewing', as: :interviewing_applicant
    patch 'applicants/:id/testing', to: 'applicants#testing', as: :testing_applicant
    patch 'applicants/:id/salary_negotiation', to: 'applicants#salary_negotiation', as: :negotiating_applicant_salary
    patch 'applicants/:id/hire', to: 'applicants#hire', as: :hire_applicant
    patch 'applicants/:id/unhire', to: 'applicants#unhire', as: :unhire_applicant
    get 'users/reset_cumulative_earnings', to: 'users#reset_cumulative_earnings', as: :reset_cumulative_earnings
    get 'notifications/:id/mark_as_read', to: 'notifications#mark_as_read', as: :mark_notification_as_read
    get 'notifications/mark_all_as_read', to: 'notifications#mark_all_as_read', as: :mark_all_as_read
    get 'notifications/mark_all_as_seen', to: 'notifications#mark_all_as_seen', as: :mark_all_as_seen
    get 'roles/set_role', to: 'roles#set_role', as: :set_role
    get 'roles/unset_role', to: 'roles#unset_role', as: :unset_role

    
    # scope module: "admin" do 
    #   resources :messages do 
    #     member do 
    #       patch 'read_by_admin_at'
    #     end
    #   end
    # end

    
    # resources :users, only: [] do 
    #   resources :companies
    # end
    resources :admin_users
    resources :users, only: [:index, :show]
    
    resources :companies do 
      resources :job_descriptions
    end

    resources :job_descriptions, only: [:index] do 
      resources :requirements, only: [:index, :show]
      resources :applicants
    end

    resources :messages

    resources :applicants, only: [] do 
      resources :comments
    end

    resources :activity_logs, only: [:index, :show]
    resources :bug_reports, only: [:index, :show]
  end

  devise_for :users, controllers: { registrations: :registrations, confirmations: :confirmations }

  root to: 'dashboard#index'
  # get 'dashboard/activity_feed', to: 'dashboard#activity_feed', as: :activity_feed
  
  patch 'companies/:id/update_button', to: 'companies#update_button', as: :update_button_for_company
  patch 'job_descriptions/:id/update_button', to: 'job_descriptions#update_button', as: :update_button_for_jd
  patch 'applicants/:id/update_button', to: 'applicants#update_button', as: :update_button_for_applicants
  patch 'requirements/:id/update_button', to: 'requirements#update_button', as: :update_button_for_rq
  patch 'qualifications/:id/update_button', to: 'qualifications#update_button', as: :update_button_for_qualification
  patch 'required_experiences/:id/update_button', to: 'required_experiences#update_button', as: :update_button_for_exp
  patch 'job_descriptions/:id/complete_job_description', to: 'job_descriptions#complete_job_description', as: :complete_jd
  patch 'job_descriptions/:id/update_job_description', to: 'job_descriptions#update_job_description', as: :update_jd
  get 'activity_feed/index', to: 'activity_feed#index', as: :activity_feed
  get 'activity_feed/show', to: 'activity_feed#show', as: :show_activity
  patch 'messages/:id/send_message', to: 'messages#send_message', as: :send_message
  patch  'messages/:id/archive_message', to: 'messages#archive_message', as: :archive_message
  patch  'messages/:id/unarchive_message', to: 'messages#unarchive_message', as: :unarchive_message
  get 'user_stats/statistics', to: 'user_stats#statistics', as: :user_stats
  patch 'users/edit_user_profile', to: 'users#edit_user_profile', as: :edit_user_profile
  patch 'bank_accounts/:id/edit_bank_details', to: 'bank_accounts#edit_bank_details', as: :edit_bank_details
  patch 'users/:id/complete_profile', to: 'users#complete_profile', as: :complete_profile
  patch 'users/:id/update_profile', to: 'users#update_profile', as: :update_profile
  get 'notifications/:id/mark_as_read', to: 'notifications#mark_as_read', as: :mark_notification_as_read
  get 'notifications/mark_all_as_read', to: 'notifications#mark_all_as_read', as: :mark_all_as_read
  get 'notifications/mark_all_as_seen', to: 'notifications#mark_all_as_seen', as: :mark_all_as_seen
  
  patch 'messages/:id/read_by_user', to: 'messages#read_by_user', as: :read_by_user


  resources :user, only: [] do 
    resources :companies, :bank_accounts 
  end

  resources :companies do 
    resources :job_descriptions
  end

  resources :job_descriptions, only: [] do 
    resources :requirements, :applicants, :qualifications, :required_experiences
  end

  resources :messages
  resources :applicants, only: [] do 
    resources :requirement_scores
  end

  resources :attachments, only: [:new, :show, :destroy] 

  match "*path", to: "application#routing_error", via: :all if Rails.env.production?
end

app/controllers/activity_feed_controller.rb
class ActivityFeedController < ApplicationController
  before_action :authenticate_user!	
  after_action :log_user_activity, only: [:index]
  
  def index
  	@feed = Activity.order(updated_at: :desc)
  	# fresh_when last_modified: @feed.maximum(:updated_at)
  end

  def show
  end


  private 

  def log_user_activity
    ActivityLogService.new({ actor: current_user, action: "viewed", resource_type: "Activities" }).log_user_activity
  end
end

app/controllers/admin/activity_feed_controller.rb
class Admin::ActivityFeedController < Admin::ApplicationController
  layout "admin"

  def index
  	@feed = Activity.order(created_at: :desc)
  end

  def show
  end
end

app/helpers/activity_feed_helper.rb
module ActivityFeedHelper
end

app/helpers/admin/activity_feed_helper.rb
module Admin::ActivityFeedHelper
end

app/views/admin/activity_feed/_added_applicant.html.erb
<tr>
	<% if !activity.trackable.nil? %>
	<td><span class="btn btn-primary btn-xs btn-round"><%= activity.user.username %></span> just brought in
		<% if activity.trackable.user != current_user %>
		<span class="dropdown">
			<% if activity.trackable.company.deal? %>
			<a href="#" class="dropdown-toggle btn btn-warning btn-xs btn-round" data-toggle="dropdown">
				<% else %>
				<a href="#" class="dropdown-toggle btn btn-default btn-xs btn-round" data-toggle="dropdown"> 	
					<% end %>  

					<%= activity.trackable.name %>
				</a>
			</span> to 
			<% if activity.trackable.company.deal? %>
			<%=link_to activity.trackable.company.company_name, admin_company_url(activity.trackable.company ,tab: "company"), class: "btn btn-success btn-xs btn-round" %>
			<% else %>  
			<%=link_to activity.trackable.company.company_name, admin_company_url(activity.trackable.company ,tab: "company"), class: "btn btn-default btn-xs btn-round" %>
			<% end %>  
			for a role as: 
			<% if activity.trackable.company.deal? %>
			<span class="btn btn-info btn-xs btn-round">
				<% else %>  
				<span class="btn btn-default btn-xs btn-round">
					<% end %>  	
					<%= activity.trackable.job_description.job_title %></span>
					<% else %>
					
					<% if activity.trackable.company.deal? %>
					<span class="btn btn-warning btn-xs btn-round">
						<% else %>  
						<span class="btn btn-default btn-xs btn-round">
							<% end %>  	

							<%= activity.trackable.name %>	
						</span>
						to <%=link_to activity.trackable.company.company_name, admin_company_url(activity.trackable ,tab: "company"), class: "btn btn-success btn-xs btn-round" %> for a role as: <span class="btn btn-info btn-xs btn-round"><%= activity.trackable.job_description.job_title %></span>
						<% end %>	
					</td>
					<td>
						<button class="btn btn-default btn-sm btn-round">	
							<%= activity.updated_at.strftime("%B %d, %Y") %> at <%= activity.updated_at.strftime("%r") %>
						</button>  
					</td>
					<% end %>	
				</tr>	

app/views/admin/activity_feed/_created_company.html.erb
<tr>
	<% if !activity.trackable.nil? %>
	<td><span class="btn btn-primary btn-xs btn-round"><%= activity.user.username %></span> just brought in <span class="text-primary"><%= link_to activity.trackable.company_name, admin_company_url(activity.trackable ,tab: "company"), class: "btn btn-success btn-xs btn-round" %></span> 
		NOTE: no deal has been made yet!
	</td> 
	<td>
		<button class="btn btn-default btn-xs btn-round">	
			<%= activity.updated_at.strftime("%B %d, %Y") %> at <%= activity.updated_at.strftime("%r") %>
		</button>  
	</td> 
	<% end %>	
</tr>

app/views/admin/activity_feed/_created_job_description.html.erb
<tr>
	<% if !activity.trackable.nil? %>
	<td><span class="btn btn-success btn-xs btn-round"><%= activity.trackable.company.company_name %></span> is looking for <%= pluralize(activity.trackable.vacancies, "applicant") %> to fill the role of
		<% if activity.trackable.company.user != current_user %>
		<span class="dropdown">
			<a href="#" class="dropdown-toggle btn btn-info btn-xs btn-round" data-toggle="dropdown">
				<%= activity.trackable.job_title %>
			</a>
		</span>
		<% else %>
		<span class="btn btn-info btn-xs btn-round"><%= activity.trackable.job_title %></span>
		<% end %>
	</td>
	<td>
		<button class="btn btn-default btn-sm btn-round">	
			<%= activity.updated_at.strftime("%B %d, %Y") %> at <%= activity.updated_at.strftime("%r") %>
		</button>  
	</td>
	<% end %>	
</tr>

app/views/admin/activity_feed/_deal_with_company.html.erb
					  <tr>
					  	<% if !activity.trackable.nil? %>
					  	<td><span class="btn btn-primary btn-xs btn-round">The Agency</span> just made a deal with
					  		<% if activity.trackable.user != current_user %>
					  		<span class="dropdown">
					  			<a href="#" class="dropdown-toggle btn btn-success btn-xs btn-round" data-toggle="dropdown">
					  				<%= activity.trackable.company_name %>
					  			</a>
					  		</span>
					  		<% else %>
					  		<span class="text-primary btn btn-success btn-xs btn-round"><%= activity.trackable.company_name %>	
					  		</span>
					  		<% end %> brought in by <span class="btn btn-primary btn-xs btn-round"><%= activity.trackable.user.username %></span>
					  	</td>
					  	<td>
					  		<button class="btn btn-default btn-sm btn-round">	
					  			<%= activity.updated_at.strftime("%B %d, %Y") %> at <%= activity.updated_at.strftime("%r") %>
					  		</button>  
					  	</td>
					  	<% end %>	
					  </tr>

app/views/admin/activity_feed/_inactive_company.html.erb
<tr>
	<% if !activity.trackable.nil? %>
	<td><span class="btn btn-primary btn-xs btn-round">The Agency</span> just made a deal with
		<% if activity.trackable.user != current_user %>
		<span class="dropdown">
			<a href="#" class="dropdown-toggle btn btn-default btn-xs btn-round" data-toggle="dropdown">
				<%= activity.trackable.company_name %>
			</a>
		</span>
		<% else %>
		<span class="text-primary btn btn-default btn-xs btn-round"><%= activity.trackable.company_name %>	
		</span>
		<% end %> brought in by <span class="btn btn-primary btn-xs btn-round"><%= activity.trackable.user.username %></span>
	</td>
	<td>
		<button class="btn btn-default btn-sm btn-round">	
			<%= activity.updated_at.strftime("%B %d, %Y") %> at <%= activity.updated_at.strftime("%r") %>
		</button>  
	</td>
	<% end %>	
</tr>

app/views/admin/activity_feed/_inactive_job_description.html.erb
<tr>
	<% if !activity.trackable.nil? %>
	<td>
		<% if activity.action = "inactive" %> 	
		<span class="btn btn-default btn-xs btn-round">
			<% else %>
			<span class="btn btn-success btn-xs btn-round">  
				<% end %>  	
				<%= activity.trackable.company.company_name %></span> is looking for <%= pluralize(activity.trackable.vacancies, "applicant") %> to fill the role of
				<% if activity.trackable.company.user != current_user %>
				<span class="dropdown">
					<a href="#" class="dropdown-toggle btn btn-default btn-xs btn-round" data-toggle="dropdown">
						<%= activity.trackable.job_title %>
					</a>
				</span>
				<% else %>
				<span class="btn btn-default btn-xs btn-round"><%= activity.trackable.job_title %></span>
				<% end %>
			</td>
			<td>
				<button class="btn btn-default btn-sm btn-round">	
					<%= activity.updated_at.strftime("%B %d, %Y") %> at <%= activity.updated_at.strftime("%r") %>
				</button>  
			</td>
			<% end %>	
		</tr>

app/views/admin/activity_feed/_no_deal_with_company.html.erb
<tr>
	<% if !activity.trackable.nil? %>
	<td><span class="btn btn-primary btn-xs btn-round"><%= activity.user.username %></span> just brought in <span class="text-primary"><%= link_to activity.trackable.company_name, admin_company_url(activity.trackable ,tab: "company"), class: "btn btn-default btn-xs btn-round" %></span> 
		NOTE: This deal has been cancelled.!
	</td> 
	<td>
		<button class="btn btn-default btn-sm btn-round">	
			<%= activity.updated_at.strftime("%B %d, %Y") %> at <%= activity.updated_at.strftime("%r") %>
		</button>  
	</td> 
	<% end %>	
</tr>	

app/views/admin/activity_feed/_not_hired_vs_hired_applicant.html.erb
<tr>
	<% if !activity.trackable.nil? %>
	<td>
		<% if activity.trackable.user != current_user %>
		<span class="dropdown">
			<% if activity.trackable.company.deal? %>
			<a href="#" class="dropdown-toggle btn btn-warning btn-xs btn-round" data-toggle="dropdown">
				<% else %>
				<a href="#" class="dropdown-toggle btn btn-default btn-xs btn-round" data-toggle="dropdown"> 	
					<% end %>  

					<%= activity.trackable.name %>
				</a>
			</span> 
			<% if activity.action == "hired" %> 
			just got
			<button class="btn btn-success btn-xs btn-round">
				<% elsif activity.action == "not hired" %>
				was
				<button class="btn btn-danger btn-xs btn-round">
					<% end %>	
					<%= activity.action %>
				</button>
				for a role as: 
				<% if activity.trackable.company.deal? %>
				<span class="btn btn-info btn-xs btn-round">
					<% else %>  
					<span class="btn btn-default btn-xs btn-round">
						<% end %>  	
						<%= activity.trackable.job_description.job_title %></span>
						<% else %>
						
						<% if activity.trackable.company.deal? %>
						<span class="btn btn-warning btn-xs btn-round">
							<% else %>  
							<span class="btn btn-default btn-xs btn-round">
								<% end %>  	

								<%= activity.trackable.name %>	
							</span>
							to <%=link_to activity.trackable.company.company_name, admin_company_url(activity.trackable ,tab: "company"), class: "btn btn-success btn-xs btn-round" %> for a role as: <span class="btn btn-info btn-xs btn-round"><%= activity.trackable.job_description.job_title %></span>
							<% end %>	
						</td>
						<td>
							<button class="btn btn-default btn-sm btn-round">	
								<%= activity.updated_at.strftime("%B %d, %Y") %> at <%= activity.updated_at.strftime("%r") %>
							</button>  
						</td>
						<% end %>	
					</tr>	

app/views/admin/activity_feed/_updated_applicant.html.erb
<tr>
	<% if !activity.trackable.nil? %>
	<td><span class="btn btn-primary btn-xs btn-round"><%= activity.user.username %></span> just brought in
		<% if activity.trackable.user != current_user %>
		<span class="dropdown">
			<a href="#" class="dropdown-toggle btn btn-success btn-xs btn-round" data-toggle="dropdown">
				<%= activity.trackable.name %>
			</a>
		</span> to <%=link_to activity.trackable.company.company_name, admin_company_url(activity.trackable.company ,tab: "company"), class: "btn btn-success btn-xs btn-round" %> for a role as: <span class="btn btn-default btn-xs btn-round"><%= activity.trackable.job_description.job_title %></span>
		<% else %>
		<span class="text-primary btn btn-success btn-xs btn-round"><%= activity.trackable.name %>	
		</span>
		to <%=link_to activity.trackable.company.company_name, admin_company_url(activity.trackable ,tab: "company"), class: "btn btn-success btn-xs btn-round" %> for a role as: <span class="btn btn-default btn-xs btn-round"><%= activity.trackable.job_description.job_title %></span>
		<% end %>	
	</td>
	<td>
		<button class="btn btn-default btn-sm btn-round">	
			<%= activity.updated_at.strftime("%B %d, %Y") %> at <%= activity.updated_at.strftime("%r") %>
		</button>  
	</td>
	<% end %>	
</tr>

app/views/admin/activity_feed/index.html.erb
<div class="col-md-12">
	<div class="card">
		<div class="card-header" data-background-color="purple">
			<h4 class="title">News Feed</h4>
			<p class="category">Real life feed of activities</p>
		</div>
		<div class="card-content table-responsive">
			<table class="table">
				<thead class="text-primary">
					<th>Stories</th>
					<th>Timestamp</th>
				</thead>
				<tbody>
				<% if @feed.any? %>
				<% @feed.each do |activity| %>
				   <% if activity.action == "create" && activity.trackable_type == "Company" %>    
					 
					 <%= render "created_company", activity: activity %>
				   
				   <% elsif activity.action == "no deal" && activity.trackable_type == "Company" %>    
					
					 <%= render "no_deal_with_company", activity: activity %>

				   <% elsif activity.action == "deal" && activity.trackable_type == "Company" %>

				     <%= render "deal_with_company", activity: activity %>

					<% elsif activity.action == "inactive" && activity.trackable_type == "Company" %>
					  
					  <%= render "inactive_company", activity: activity %>

					<% elsif activity.action == "create" && (activity.trackable_type == "JobDescription" && activity.permitted? ) %>
					
					  <%= render "created_job_description", activity: activity %>	

				   <% elsif activity.action == "added an applicant" && activity.trackable_type == "Applicant" %>
				   
				     <%= render "added_applicant", activity: activity %>	

					<% elsif (activity.action == "not hired" || activity.action == "hired") && activity.trackable_type == "Applicant" %>
					
					  <%= render "not_hired_vs_hired_applicant", activity: activity %>
					
					<% elsif activity.action == "update" && activity.trackable_type == "Applicant" %>
					
					  <%= render "updated_applicant", activity: activity %>	
					
					<% elsif activity.action == "inactive" && activity.trackable_type == "JobDescription" %>
					  
					  <%= render "inactive_job_description", activity: activity %>

				  <% end %>	
				<% end %>

				<% else %>
			    <tr>
			    	<td>no data</td>
			    	<td>no data</td>
			    </tr>	
				<% end %>
				</tbody>
			</table>

		</div>
	</div>
</div>
<%= javascript_include_tag "admin/jquery-3.1.0.min" %>
<%= javascript_include_tag "admin/bootstrap.min" %>
<%= javascript_include_tag "admin/material.min" %>
<%= javascript_include_tag "admin/chartist.min" %>
<%= javascript_include_tag "admin/bootstrap-notify" %>
<%= javascript_include_tag "admin/material-dashboard" %>

app/views/admin/activity_feed/show.html.erb
<h1>Admin::ActivityFeed#show</h1>
<p>Find me in app/views/admin/activity_feed/show.html.erb</p>