config/routes.rb
Rails.application.routes.draw do

  get 'bug_report/show'

  namespace :admin do
  get 'bug_reports/index'
  end

  namespace :admin do 
    get 'dashboard/dashboard', to: 'dashboard#dashboard', as: :dashboard
    # get 'dashboard/activity_feed', to: 'dashboard#activity_feed', as: :activity_feed
    patch 'companies/:id/update_button', to: 'companies#update_button', as: :update_button_for_company
    patch 'companies/:id/contact_company', to: 'companies#contact_company', as: :contact_company
    patch 'companies/:id/allow_changes_to_company', to: 'companies#allow_changes_to_company', as: :allow_changes_to_company
    patch 'companies/:id/deal_with_company', to: 'companies#deal_with_company', as: :deal_with_company

    patch 'job_descriptions/:id/update_button', to: 'job_descriptions#update_button', as: :update_button_for_jd
    patch 'job_descriptions/:id/allow_changes_to_jd', to: 'job_descriptions#allow_changes_to_jd', as: :allow_changes_to_jd
    patch 'applicants/:id/allow_changes_to_applicant', to: 'applicants#allow_changes_to_applicant', as: :allow_changes_to_applicant

    patch 'qualifications/:id/allow_changes_to_qualification', to: 'qualifications#allow_changes_to_qualification', as: :allow_changes_to_qualification
    patch 'required_experiences/:id/allow_changes_to_req_exp', to: 'required_experiences#allow_changes_to_req_exp', as: :allow_changes_to_req_exp
    patch 'requirements/:id/allow_changes_to_requirement', to: 'requirements#allow_changes_to_requirement', as: :allow_changes_to_requirement

    patch 'admin_users/:id/update_button', to: 'admin_users#update_button', as: :update_button_for_admin
    get 'activity_feed/index', to: 'activity_feed#index', as: :activity_feed
    get 'activity_feed/show', to: 'activity_feed#show', as: :show_activity
    patch 'messages/:id/send_message', to: 'messages#send_message', as: :send_message
    patch  'messages/:id/archive_message', to: 'messages#archive_message', as: :archive_message
    patch  'messages/:id/unarchive_message', to: 'messages#unarchive_message', as: :unarchive_message
    patch 'applicants/:id/update_salary', to: 'applicants#update_salary', as: :update_salary
    patch 'applicants/:id/update_button', to: 'applicants#update_button', as: :update_button_for_applicants
    get 'applicants/all_applicants', to: 'applicants#all_applicants', as: :manage_all_applicants
    patch 'users/:id/approve', to: 'users#approve', as: :approve_user
    patch 'users/:id/disapprove', to: 'users#disapprove', as: :disapprove_user
    patch 'applicants/:id/shortlist', to: 'applicants#shortlist', as: :shortlist_applicant
    patch 'applicants/:id/interviewing', to: 'applicants#interviewing', as: :interviewing_applicant
    patch 'applicants/:id/testing', to: 'applicants#testing', as: :testing_applicant
    patch 'applicants/:id/salary_negotiation', to: 'applicants#salary_negotiation', as: :negotiating_applicant_salary
    patch 'applicants/:id/hire', to: 'applicants#hire', as: :hire_applicant
    patch 'applicants/:id/unhire', to: 'applicants#unhire', as: :unhire_applicant
    get 'users/reset_cumulative_earnings', to: 'users#reset_cumulative_earnings', as: :reset_cumulative_earnings
    get 'notifications/:id/mark_as_read', to: 'notifications#mark_as_read', as: :mark_notification_as_read
    get 'notifications/mark_all_as_read', to: 'notifications#mark_all_as_read', as: :mark_all_as_read
    get 'notifications/mark_all_as_seen', to: 'notifications#mark_all_as_seen', as: :mark_all_as_seen
    get 'roles/set_role', to: 'roles#set_role', as: :set_role
    get 'roles/unset_role', to: 'roles#unset_role', as: :unset_role

    
    # scope module: "admin" do 
    #   resources :messages do 
    #     member do 
    #       patch 'read_by_admin_at'
    #     end
    #   end
    # end

    
    # resources :users, only: [] do 
    #   resources :companies
    # end
    resources :admin_users
    resources :users, only: [:index, :show]
    
    resources :companies do 
      resources :job_descriptions
    end

    resources :job_descriptions, only: [:index] do 
      resources :requirements, only: [:index, :show]
      resources :applicants
    end

    resources :messages

    resources :applicants, only: [] do 
      resources :comments
    end

    resources :activity_logs, only: [:index, :show]
    resources :bug_reports, only: [:index, :show]
  end

  devise_for :users, controllers: { registrations: :registrations, confirmations: :confirmations }

  root to: 'dashboard#index'
  # get 'dashboard/activity_feed', to: 'dashboard#activity_feed', as: :activity_feed
  
  patch 'companies/:id/update_button', to: 'companies#update_button', as: :update_button_for_company
  patch 'job_descriptions/:id/update_button', to: 'job_descriptions#update_button', as: :update_button_for_jd
  patch 'applicants/:id/update_button', to: 'applicants#update_button', as: :update_button_for_applicants
  patch 'requirements/:id/update_button', to: 'requirements#update_button', as: :update_button_for_rq
  patch 'qualifications/:id/update_button', to: 'qualifications#update_button', as: :update_button_for_qualification
  patch 'required_experiences/:id/update_button', to: 'required_experiences#update_button', as: :update_button_for_exp
  patch 'job_descriptions/:id/complete_job_description', to: 'job_descriptions#complete_job_description', as: :complete_jd
  patch 'job_descriptions/:id/update_job_description', to: 'job_descriptions#update_job_description', as: :update_jd
  get 'activity_feed/index', to: 'activity_feed#index', as: :activity_feed
  get 'activity_feed/show', to: 'activity_feed#show', as: :show_activity
  patch 'messages/:id/send_message', to: 'messages#send_message', as: :send_message
  patch  'messages/:id/archive_message', to: 'messages#archive_message', as: :archive_message
  patch  'messages/:id/unarchive_message', to: 'messages#unarchive_message', as: :unarchive_message
  get 'user_stats/statistics', to: 'user_stats#statistics', as: :user_stats
  patch 'users/edit_user_profile', to: 'users#edit_user_profile', as: :edit_user_profile
  patch 'bank_accounts/:id/edit_bank_details', to: 'bank_accounts#edit_bank_details', as: :edit_bank_details
  patch 'users/:id/complete_profile', to: 'users#complete_profile', as: :complete_profile
  patch 'users/:id/update_profile', to: 'users#update_profile', as: :update_profile
  get 'notifications/:id/mark_as_read', to: 'notifications#mark_as_read', as: :mark_notification_as_read
  get 'notifications/mark_all_as_read', to: 'notifications#mark_all_as_read', as: :mark_all_as_read
  get 'notifications/mark_all_as_seen', to: 'notifications#mark_all_as_seen', as: :mark_all_as_seen
  
  patch 'messages/:id/read_by_user', to: 'messages#read_by_user', as: :read_by_user


  resources :user, only: [] do 
    resources :companies, :bank_accounts 
  end

  resources :companies do 
    resources :job_descriptions
  end

  resources :job_descriptions, only: [] do 
    resources :requirements, :applicants, :qualifications, :required_experiences
  end

  resources :messages
  resources :applicants, only: [] do 
    resources :requirement_scores
  end

  resources :attachments, only: [:new, :show, :destroy] 

  match "*path", to: "application#routing_error", via: :all if Rails.env.production?
end

app/models/qualification.rb
class Qualification < ActiveRecord::Base
  belongs_to :job_description
  validates :certificate, :field_of_study, presence: true

  def updated?
  	self.update_button?
  end
end

app/controllers/admin/qualifications_controller.rb
class Admin::QualificationsController < ApplicationController
  before_action :set_admin_authorization_parameters, only: [:allow_changes_to_qualification]
  layout "admin"

  
  def allow_changes_to_qualification
  	@qualification = @qualification = Qualification.find(params[:id])
  	@qualification_copy = if qualification_copy = Qualification.find_by(copy: true, copy_id: @qualification.id)
                            qualification_copy
                          end 
    
    if (@qualification.certificate != @qualification_copy.certificate) || (@qualification.field_of_study != @qualification_copy.field_of_study)

      qualification_copy_attributes = @qualification_copy.attributes 
      qualification_copy_attributes.delete("id")
      qualification_copy_attributes["copy"] = false 
      qualification_copy_attributes["copy_id"] = nil 
      @qualification.update(qualification_copy_attributes)
      @qualification_copy.delete
      AuthorizeQualificationUpdateNotificationService.new({ actor: current_user, action: "authorize", resource: @qualification, resource_type: @qualification.class.name }).notify_user 
      flash[:success] = "changes have been incorporated."
    end     
    redirect_to :back 
  end


  private 

  def set_admin_authorization_parameters 
    @qualification = Qualification.find(params[:id])
  	Authorization::AdminAuthorizationPolicy.new(current_user, @qualification, @qualification.class.name, self).implement_authorization_policy
  end
end

app/controllers/qualifications_controller.rb
class QualificationsController < ApplicationController
  before_action :authenticate_user!
  before_action :prevent_addition_of_new_qualification_if_jd_has_applicants, only: [:new, :create]
  before_action :prevent_deletion_of_qualifications_if_jd_has_applicants, only: [:destroy]
  before_action :copy_changes_to_existing_object, only: [:update]
  before_action :set_jd, except: [:update_button] 
  before_action :set_qualification, only: [:show, :edit, :update, :destroy]


  def index
  	@qualifications = @jd.qualifications.all
  end

  def show
  end

  def new
  	@qualification = @jd.qualifications.build
  end

  def create
  	@qualification = @jd.qualifications.build(qualification_params)
    
    if params[:commit] == "proceed later"
      if @qualification.certificate.blank? && @qualification.field_of_study.blank?
        flash[:alert] = "no qualification was saved."
        redirect_to [@jd.company, @jd]
      else
        if @qualification.save 
          implement_authorization_policy_if_applicable @qualification
          on_success "your qualification was saved", [@jd.company, @jd]
        else
          on_failure "oops! something went wrong", :new
        end  
      end
    elsif params[:commit] == "Next"
      if @qualification.certificate.blank? && @qualification.field_of_study.blank?
        redirect_to new_job_description_required_experience_url(@jd)
      else
        if @qualification.save 
          implement_authorization_policy_if_applicable @qualification
          on_success "added qualification successfully", new_job_description_required_experience_url(@jd) 
        else
          on_failure "oops! something went wrong for the reasons below:", :new
        end
      end
    elsif params[:commit] == "Save and Add Another Qualification"
      if @qualification.save 
        implement_authorization_policy_if_applicable @qualification
        on_success "added qualification successfully", new_job_description_qualification_url(@jd) 
      else
        on_failure "oops! you can't add another qualification for the reasons below:", :new
      end  
    end
  end

  def edit
  end

  def update
  	if @qualification.update(qualification_params)
  	   @qualification.update(update_button: false)	
  	  flash[:success] = "successfully updated qualification"
  	  
  	  if request.referrer == company_job_description_url(@jd.company, @jd)
  	  	redirect_to :back
  	  else
  	    redirect_to job_description_qualifications_url(@jd)
  	  end
  	else 
      on_failure  "oops! something went wrong", :edit
  	end
  end

  def destroy
    delete_copy_of_resource @qualification
  	@qualification.destroy
    on_success "successfully deleted a qualification", :back
  end

  def update_button
  	@qualification = Qualification.find(params[:id])
  	@qualification.update(update_button: true)
  	redirect_to :back
  end


  
  private 

  def set_jd
  	@jd = JobDescription.find(params[:job_description_id])
  end

  def set_qualification
  	set_jd
  	@qualification = @jd.qualifications.find(params[:id])
  end

  def qualification_params
  	params.require(:qualification).permit(:certificate, :field_of_study,
  	 :update_button)
  end

  def copy_changes_to_existing_object
    @qualification = Qualification.find(params[:id])
    if @qualification.job_description.applicants.any? 
      existing_attributes = @qualification.attributes 
      update_attributes = qualification_params 
      ["id", "job_description_id", "created_at", "updated_at", "copy", "copy_id", "update_button"].each do |key|
        existing_attributes.delete(key)
      end
      if change_in_data existing_attributes, update_attributes
        if find_qualification_copy = Qualification.find_by(copy: true, copy_id: @qualification.id)
          find_qualification_copy.delete
          @qualification_copy = Qualification.create qualification_params
          @qualification_copy.update(copy: true, copy_id: @qualification.id, job_description_id: @qualification.job_description_id)
        else
          @qualification_copy = Qualification.create qualification_params
          @qualification_copy.update(copy: true, copy_id: @qualification.id, job_description_id: @qualification.job_description_id)
        end
        flash[:warning] = "your changes have been saved pending admin authorization."
        @qualification.update(update_button: false)
        redirect_to company_job_description_url @qualification.job_description.company, @qualification.job_description
      else
        @qualification.update(update_button: false)
        flash[:alert] = "no changes detected"
        redirect_to company_job_description_url @qualification.job_description.company, @qualification.job_description
      end
    else
      # @qualification.job_description.update(update_button: false) 
      # @qualification.update(update_button: false)
      # redirect_to company_job_description_url @qualification.job_description.company, @qualification.job_description
    end
  end

  def prevent_addition_of_new_qualification_if_jd_has_applicants
    @job_description = JobDescription.find(params[:job_description_id])
    if @job_description.applicants.any? 
      flash[:alert] = "you can not add new qualifications since job description has associated applicants. However, you can make edits to existing qualifications."
      redirect_to :back
    end
  end

  def prevent_deletion_of_qualifications_if_jd_has_applicants
    @job_description = JobDescription.find(params[:job_description_id])
    if @job_description.applicants.any? 
      flash[:alert] = "you can not delete any qualification since this job description has associated applicants. However, you can make edits to existing qualifications."
      redirect_to :back
    end
  end
end

app/helpers/admin/qualifications_helper.rb
module Admin::QualificationsHelper
end

app/helpers/qualifications_helper.rb
module QualificationsHelper
end

app/views/qualifications/_form.html.erb
<div class="col-md-8">
	<div class="card">
		<div class="card-header" data-background-color="purple">
			<h4 class="title">
		    <% if @qualification.persisted? %>
		      Edit
		    <% else %>
		      Add a 
		    <% end %>
			Qualification for the role of <%= @jd.job_title %> at <%= @jd.company.company_name %></h4>
		</div>
		<div class="card-content">
			<%= simple_form_for([jd, qualification]) do |f| %>
			<% if f.object.errors.any? %>
			<div class="alert alert-danger">  
				<% f.object.errors.full_messages.uniq.each do |msg| %>
				  <%= msg %>
				<br>
				<% end %>
			</div> 
			<% end %>

			<div class="row">
			  <div class="col-md-12">
				<% @q = 0 %>
			    <% if @jd.qualifications.any? %>
			      <% @jd.qualifications.where(copy: false).each do |qualification| %>
				  <% @q += 1 %>	
				  <div class="row">
				    <td class="col-md-1"><%= @q %>. <%= qualification.certificate %></td> <td class="col-md-1">in</td> <td class="col-md-4"><%= qualification.field_of_study %></td> 
				  </div>  
				  <% end %>
				<% end %>
			  </div>	
			</div>

			<div class="row">
				<div class="col-md-2">
					<div class="form-group label-floating">
						<label class="control-label">Degree</label>
						<%= f.input :certificate, placeholder: "BSc", label: false, class: "form-control" %>
					</div>
				</div>
				<div class="col-md-4">
					<div class="form-group label-floating">
						<label class="control-label">Field of study/Course</label>
						<%= f.input :field_of_study, placeholder: "Accounting", label: false, class: "form-control" %>
					</div>
				</div>
			</div>


			<div class="row">
			  <%= link_to "return to JD", [@jd.company, @jd], class: "btn btn-primary btn-xs btn-round" %>
			  <%= f.button :submit, "proceed later", class: "btn btn-primary btn-xs btn-round pull-right" %>
			  <%= f.button :submit, "Next", class: "btn btn-primary btn-xs btn-round pull-right" %>
			  <%= f.button :submit, "Save and Add Another Qualification", class: "btn btn-primary btn-xs btn-round pull-right" %>			
			</div>
			<% end %>
		</div>
	</div>
</div>

app/views/qualifications/edit.html.erb
<%= render "form", jd: @jd, qualification: @qualification %>

app/views/qualifications/index.html.erb
<div class="col-md-12">
	<div class="card">
		<div class="card-header" data-background-color="purple">
			<h4 class="title">Required Qualifications for role as <%= @jd.job_title %> at 
		    <% if @jd.company.user == current_user %>		
			  <%= @jd.company.company_name %>/<%= @jd.company.alias_name %>
			<% else %>
			  <%= @jd.company.alias_name %>  
			<% end %>
			 </h4>
		</div>
		<div class="card-content table-responsive">
			<table class="table">
				<thead class="text-primary">
					<th></th>
					<th>Certificate</th>
					<th>Field Of Study</th>
					<th></th>
				</thead>
				<% if @qualifications.any? %>
				<tbody>
					<% @no = 0 %>
					<% @qualifications.each do |qualification| %>
					<% @no += 1 %>
					<% if qualification.updated? %>
					  	<%= simple_form_for([@jd, qualification]) do |f| %>
					  	<tr>
					  	  <td><%= @no %></td>
					  	  <td><%= f.input :certificate, label: false, class: "form-control" %></td>
					  	  <td><%= f.input :field_of_study, label: false, class: "form-control" %></td>
					  	  <td><%= f.button :submit, "update", class: "btn btn-primary  btn-xs btn-round pull-right" %></td>
					  	</tr>
					  	<% end %>
					<% else %>
					<tr>
						<td><%= @no %></td>
						<td><%= qualification.certificate %></td>
						<td><%= qualification.field_of_study %></td>
						<td>
						<% if @jd.company.user == current_user %>
							<%= link_to update_button_for_qualification_url(qualification), method: :patch do %>
							<button type="button" title="Edit Task" class="btn btn-primary btn-simple btn-xs">
								<i class="material-icons">edit</i>
							</button>  
							<% end %>	
							<%= link_to job_description_qualification_url(@jd, qualification), method: :delete, data: { confirm: "Are you sure?" } do %>
							<button type="button" title="Remove" class="btn btn-primary btn-simple btn-xs">
								<i class="material-icons">close</i>
							</button>  
							<% end %>	
						<% end %>	
						</td>
					</tr>
					<% end %>
					<% end %>
					<% else %>
					<tr>
						<td></td>
						<td>no content</td>
						<td></td>	
					</tr>					
				</tbody>
				<% end %>
			</table>
			<div class="row">
			<% if @jd.company.user == current_user %>
			  <% if @jd.qualifications.any? %>
				<%= link_to new_job_description_qualification_url(@jd), class: "btn btn-primary btn-xs btn-round pull-right" do %>
				  <i class="material-icons">add</i>another qualification
			    <% end %>
			  <% else %>  
			    <%= link_to new_job_description_qualification_url(@jd), class: "btn btn-primary btn-xs btn-round pull-right" do %>
				  <i class="material-icons">add</i>qualification
			    <% end %>
			  <% end %>  
			<% end %>	
			</div>
			<div class="row">
			  <%= link_to new_job_description_requirement_url(@jd), class: "btn btn-primary btn-xs btn-round pull-right" do %>
				  <i class="material-icons">add</i> requirement
			    <% end %>				
			</div>
			<div class="row">
			    <% if request.referrer == company_job_descriptions_url(@jd.company) %>
			    <%= link_to "Back", :back, class: "btn btn-primary btn-xs btn-round pull-right" %>
				<% else %>  
				  <%= link_to "Back to #{@jd.company.company_name}", company_url(@jd.company, tab: "company"), class: "btn btn-primary btn-xs btn-round pull-right" %>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/qualifications/new.html.erb
<%= render "form", jd: @jd, qualification: @qualification %>

app/views/qualifications/show.html.erb
<h1>Qualifications#show</h1>
<p>Find me in app/views/qualifications/show.html.erb</p>