config/routes.rb
Rails.application.routes.draw do

  get 'bug_report/show'

  namespace :admin do
  get 'bug_reports/index'
  end

  namespace :admin do 
    get 'dashboard/dashboard', to: 'dashboard#dashboard', as: :dashboard
    # get 'dashboard/activity_feed', to: 'dashboard#activity_feed', as: :activity_feed
    patch 'companies/:id/update_button', to: 'companies#update_button', as: :update_button_for_company
    patch 'companies/:id/contact_company', to: 'companies#contact_company', as: :contact_company
    patch 'companies/:id/allow_changes_to_company', to: 'companies#allow_changes_to_company', as: :allow_changes_to_company
    patch 'companies/:id/deal_with_company', to: 'companies#deal_with_company', as: :deal_with_company

    patch 'job_descriptions/:id/update_button', to: 'job_descriptions#update_button', as: :update_button_for_jd
    patch 'job_descriptions/:id/allow_changes_to_jd', to: 'job_descriptions#allow_changes_to_jd', as: :allow_changes_to_jd
    patch 'applicants/:id/allow_changes_to_applicant', to: 'applicants#allow_changes_to_applicant', as: :allow_changes_to_applicant

    patch 'qualifications/:id/allow_changes_to_qualification', to: 'qualifications#allow_changes_to_qualification', as: :allow_changes_to_qualification
    patch 'required_experiences/:id/allow_changes_to_req_exp', to: 'required_experiences#allow_changes_to_req_exp', as: :allow_changes_to_req_exp
    patch 'requirements/:id/allow_changes_to_requirement', to: 'requirements#allow_changes_to_requirement', as: :allow_changes_to_requirement

    patch 'admin_users/:id/update_button', to: 'admin_users#update_button', as: :update_button_for_admin
    get 'activity_feed/index', to: 'activity_feed#index', as: :activity_feed
    get 'activity_feed/show', to: 'activity_feed#show', as: :show_activity
    patch 'messages/:id/send_message', to: 'messages#send_message', as: :send_message
    patch  'messages/:id/archive_message', to: 'messages#archive_message', as: :archive_message
    patch  'messages/:id/unarchive_message', to: 'messages#unarchive_message', as: :unarchive_message
    patch 'applicants/:id/update_salary', to: 'applicants#update_salary', as: :update_salary
    patch 'applicants/:id/update_button', to: 'applicants#update_button', as: :update_button_for_applicants
    get 'applicants/all_applicants', to: 'applicants#all_applicants', as: :manage_all_applicants
    patch 'users/:id/approve', to: 'users#approve', as: :approve_user
    patch 'users/:id/disapprove', to: 'users#disapprove', as: :disapprove_user
    patch 'applicants/:id/shortlist', to: 'applicants#shortlist', as: :shortlist_applicant
    patch 'applicants/:id/interviewing', to: 'applicants#interviewing', as: :interviewing_applicant
    patch 'applicants/:id/testing', to: 'applicants#testing', as: :testing_applicant
    patch 'applicants/:id/salary_negotiation', to: 'applicants#salary_negotiation', as: :negotiating_applicant_salary
    patch 'applicants/:id/hire', to: 'applicants#hire', as: :hire_applicant
    patch 'applicants/:id/unhire', to: 'applicants#unhire', as: :unhire_applicant
    get 'users/reset_cumulative_earnings', to: 'users#reset_cumulative_earnings', as: :reset_cumulative_earnings
    get 'notifications/:id/mark_as_read', to: 'notifications#mark_as_read', as: :mark_notification_as_read
    get 'notifications/mark_all_as_read', to: 'notifications#mark_all_as_read', as: :mark_all_as_read
    get 'notifications/mark_all_as_seen', to: 'notifications#mark_all_as_seen', as: :mark_all_as_seen
    get 'roles/set_role', to: 'roles#set_role', as: :set_role
    get 'roles/unset_role', to: 'roles#unset_role', as: :unset_role

    
    # scope module: "admin" do 
    #   resources :messages do 
    #     member do 
    #       patch 'read_by_admin_at'
    #     end
    #   end
    # end

    
    # resources :users, only: [] do 
    #   resources :companies
    # end
    resources :admin_users
    resources :users, only: [:index, :show]
    
    resources :companies do 
      resources :job_descriptions
    end

    resources :job_descriptions, only: [:index] do 
      resources :requirements, only: [:index, :show]
      resources :applicants
    end

    resources :messages

    resources :applicants, only: [] do 
      resources :comments
    end

    resources :activity_logs, only: [:index, :show]
    resources :bug_reports, only: [:index, :show]
  end

  devise_for :users, controllers: { registrations: :registrations, confirmations: :confirmations }

  root to: 'dashboard#index'
  # get 'dashboard/activity_feed', to: 'dashboard#activity_feed', as: :activity_feed
  
  patch 'companies/:id/update_button', to: 'companies#update_button', as: :update_button_for_company
  patch 'job_descriptions/:id/update_button', to: 'job_descriptions#update_button', as: :update_button_for_jd
  patch 'applicants/:id/update_button', to: 'applicants#update_button', as: :update_button_for_applicants
  patch 'requirements/:id/update_button', to: 'requirements#update_button', as: :update_button_for_rq
  patch 'qualifications/:id/update_button', to: 'qualifications#update_button', as: :update_button_for_qualification
  patch 'required_experiences/:id/update_button', to: 'required_experiences#update_button', as: :update_button_for_exp
  patch 'job_descriptions/:id/complete_job_description', to: 'job_descriptions#complete_job_description', as: :complete_jd
  patch 'job_descriptions/:id/update_job_description', to: 'job_descriptions#update_job_description', as: :update_jd
  get 'activity_feed/index', to: 'activity_feed#index', as: :activity_feed
  get 'activity_feed/show', to: 'activity_feed#show', as: :show_activity
  patch 'messages/:id/send_message', to: 'messages#send_message', as: :send_message
  patch  'messages/:id/archive_message', to: 'messages#archive_message', as: :archive_message
  patch  'messages/:id/unarchive_message', to: 'messages#unarchive_message', as: :unarchive_message
  get 'user_stats/statistics', to: 'user_stats#statistics', as: :user_stats
  patch 'users/edit_user_profile', to: 'users#edit_user_profile', as: :edit_user_profile
  patch 'bank_accounts/:id/edit_bank_details', to: 'bank_accounts#edit_bank_details', as: :edit_bank_details
  patch 'users/:id/complete_profile', to: 'users#complete_profile', as: :complete_profile
  patch 'users/:id/update_profile', to: 'users#update_profile', as: :update_profile
  get 'notifications/:id/mark_as_read', to: 'notifications#mark_as_read', as: :mark_notification_as_read
  get 'notifications/mark_all_as_read', to: 'notifications#mark_all_as_read', as: :mark_all_as_read
  get 'notifications/mark_all_as_seen', to: 'notifications#mark_all_as_seen', as: :mark_all_as_seen
  
  patch 'messages/:id/read_by_user', to: 'messages#read_by_user', as: :read_by_user


  resources :user, only: [] do 
    resources :companies, :bank_accounts 
  end

  resources :companies do 
    resources :job_descriptions
  end

  resources :job_descriptions, only: [] do 
    resources :requirements, :applicants, :qualifications, :required_experiences
  end

  resources :messages
  resources :applicants, only: [] do 
    resources :requirement_scores
  end

  resources :attachments, only: [:new, :show, :destroy] 

  match "*path", to: "application#routing_error", via: :all if Rails.env.production?
end

app/controllers/admin/companies_controller.rb
class Admin::CompaniesController < Admin::ApplicationController
  before_action :set_admin_authorization_parameters, only: [:update_button, :update, :destroy, :contact_company, :deal_with_company, :allow_changes_to_company]
  before_action :set_company, only: [:show, :edit, :update, :destroy, :update_button, :contact_company,
   :deal_with_company, :allow_changes_to_company]
  layout "admin"


  def index
  	@companies = Company.all.includes(:user).where(copy: false).order(created_at: :asc)
    @company_id = params[:company_id].to_i
    @notifier_id = params[:notifier_id].to_i
  end

  def show
    @tab = params[:tab]
    @applicant_id = params[:applicant_id]

    @company_copy = if company_copy = Company.find_by(copy: true, copy_id: @company.id)
                      company_copy
                    end   
  end

  def edit
  end
  
  def update
  	if @company.update(company_params)
  	  @company.update(update_button: false, edit_user_id: nil)	
  	  flash[:success] = "you successfully updated #{@company.company_name} details"
  	  redirect_to :back
  	else
  	  flash.now[:alert] = "oops! sthg went wrong"
  	  render :edit
  	end
  end

  def destroy
    if @company.job_descriptions.any? || @company.applicants.any?
  	   flash[:alert] = "this action is not possible. This company has jds and applicants associated with it. please contact the admin for help with this issue"
       redirect_to :back
    else   
      @company.destroy
  	  flash[:success] = "succesfully deleted company"
  	  redirect_to :back
    end
  end

  def update_button
    if @company.updated? && @company.edit_user_id != current_user.id
      flash[:alert] = "can't proceed with this action. this company is currently being worked on."
      redirect_to [:admin, @company, tab: "company"]
    else   
  	  @company.update(update_button: true, edit_user_id: current_user.id)
  	  redirect_to :back
    end
  end

  def contact_company
    if @company.contacted?
      if @company.deal?
        flash[:alert] = "not applicable. A deal has already been made with #{@company.company_name}"
        redirect_to :back
      else
        @company.no_contact
        redirect_to admin_companies_url(company_id: nil)
      end 
    else
      @company.contact
      CompanyContactNotificationService.new({ actor: current_user, action: "contacted", recipient: @company.user, resource: @company,
        resource_type: @company.class.name }).notify_user
      flash[:success] = "contacted #{@company.company_name}" 
      redirect_to admin_companies_url(company_id: nil)
    end
  end

  def deal_with_company
    if @company.deal?
      if @company.job_descriptions.any? { |jd| jd.applicants.any? }
        flash[:alert] = "not applicable. Applicants have been linked with this company."
      else
        @company.no_deal
        track_activity @company, "no deal", @company.user_id 
        update_jds_of_company_in_activity @company
        update_company_in_activity @company
      end
    else
      if @company.contacted?
        @company.deal_true 
        CompanyDealNotificationService.new({ actor: current_user, action: "deal", recipient: @company.user, resource: @company,
        resource_type: @company.class.name }).notify_user
        track_activity @company, "deal", @company.user_id 
        permit_jds_of_company_in_activity @company
        flash[:success] = "you and #{@company.company_name} have a deal"
      else
        flash[:alert] = "not applicable. you haven't contacted #{@company.company_name} yet"
      end
    end
    redirect_to :back
  end

  def allow_changes_to_company
     @company_copy = if company_copy = Company.find_by(copy: true, copy_id: @company.id)
                      company_copy
                    end   
     if company_attributes_not_equal_to_company_copy_attributes

       company_copy_attributes = @company_copy.attributes 
       company_copy_attributes.delete("id")
       company_copy_attributes["copy"] = false 
       company_copy_attributes["copy_id"] = nil
       @company.update(company_copy_attributes)
       @company_copy.delete
       AuthorizeCompanyUpdateNotificationService.new({ actor: current_user, action: "authorize", resource: @company, resource_type: @company.class.name }).notify_user
       flash[:success] = "changes have been incorporated."
     end
     redirect_to :back
  end
 


  private

  def company_attributes_not_equal_to_company_copy_attributes
     (@company.company_name != @company_copy.company_name) || (@company.clientname != @company_copy.clientname) || (@company.email != 
      @company_copy.email) || (@company.role != @company_copy.role) || (@company.phonenumber != @company_copy.phonenumber) || (@company.url != 
      @company_copy.url) || (@company.about != @company_copy.about)
  end

  def set_company
  	@company = Company.find(params[:id])
  end

  def company_params
    params.require(:company).permit(:company_name, :clientname, :email, :phonenumber, :role,
  	:url, :about, :contacted, :deal, :edit_user_id)
  end

  def permit_jds_of_company_in_activity(company)
    company.job_descriptions.each do |jd|
      track_activity jd, "create", jd.user_id if jd.completed?
    end
  end

  def update_jds_of_company_in_activity(company)
    company.job_descriptions.each do |jd|
      if activity_exists? jd, "JobDescription", "create"
        activity = Activity.find_by trackable_id: jd.id, trackable_type: "JobDescription", action: "create"
         activity.update(action: "inactive") 
      end
    end  
  end

  def update_company_in_activity(company)
    if activity_exists? company, "Company", "deal"
      activity = Activity.find_by trackable_id: company.id, trackable_type: "Company", action: "deal"
      activity.update(action: "inactive")
    end
  end

  def set_admin_authorization_parameters
    @company = Company.find(params[:id])
    Authorization::AdminAuthorizationPolicy.new(current_user, @company, "Company", self).implement_authorization_policy
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :authenticate_user!
  before_action :copy_changes_to_existing_object, only: [:update] 
  before_action :set_company, only: [:show, :edit, :update, :destroy, :update_button]

  def index
  	@companies = current_user.companies.where(copy: false)
    @applicants = current_user.applicants.where(copy: false)
  end

  def show
    @tab = params[:tab]
  end

  def new
  	@company = current_user.companies.build
  end

  def create
  	@company = current_user.companies.build(company_params)

  	if @company.save
      create_alias_name_for_company @company
      track_activity @company, params[:action], @company.user.id  
      CompanyCreateNotificationService.new({ actor: current_user, action: "created", resource: @company, resource_type: @company.class.name }).notify_admins
      on_success "you succesfully created a company with name #{@company.company_name}", new_company_job_description_url(company_id: @company)
  	else
      on_failure "oops! something went wrong", :new
  	end
  end

  def edit
  end

  def update
  	if @company.update(company_params)
  	  @company.update(update_button: false)	
      create_alias_name_for_company @company
      track_activity @company, params[:action], @company.user.id
      on_success "you successfully updated #{@company.company_name} details", company_url(@company, tab: "company") 
  	else
  	  flash[:errors] = "ooops! something went wrong"
  	  render :edit
  	end
  end

  def destroy
    if @company.job_descriptions.any? || @company.applicants.any?
      flash[:alert] = "can't proceed with this action. this company has associated applicants/job descriptions. please contact the admin for help with this."
    else  
  	  @company.destroy
    	flash[:success] = "succesfully deleted company"
  	end
    redirect_to :back
  end

  def update_button
  	@company.update(update_button: true)
    if request.referrer == user_companies_url(@company.user)
      redirect_to [@company, tab: "company"]
    else
  	  redirect_to :back
    end
  end


  private

  def set_company
    if current_user.companies.include? @company
  	  @company = current_user.companies.find(params[:id])
    else
      @company = Company.find(params[:id])
    end
  end

  def company_params
    params.require(:company).permit(:company_name, :clientname, :email, :phonenumber, :role,
  	:url, :about, :alias_name, :industry_id)
  end

  def create_alias_name_for_company(company)
    @random = SecureRandom.hex(2)
    id = params[:company][:industry_id].to_i
    @industry = Industry.find(id)
    @company.update(alias_name: @industry.name + "-#{@random}")
  end

  def copy_changes_to_existing_object
    @company = Company.find(params[:id])
    @existing_attributes = @company.attributes 
    @update_attributes = company_params 
    @update_attributes["industry_id"] = @update_attributes["industry_id"].to_i
    ["id", "user_id", "copy", "copy_id", "contacted", "created_at", "updated_at", "deal", "edit_user_id", "alias_name", "update_button", "commit"].each do |key|
      @existing_attributes.delete key
    end

    if change_in_data @existing_attributes, @update_attributes
      if @company.job_descriptions.any?
        if find_company = Company.find_by(copy: true, copy_id: @company.id)
          find_company.delete 
          @company_copy = Company.create company_params
          @company_copy.update(copy: true, copy_id: @company.id, user_id: @company.user_id, alias_name: @company.alias_name, contacted: @company.contacted, deal: @company.deal)
        else
          @company_copy = Company.create company_params
          @company_copy.update(copy: true, copy_id: @company.id, user_id: @company.user_id, alias_name: @company.alias_name, contacted: @company.contacted, deal: @company.deal)
        end
        @company.update(update_button: false) 
        CompanyUpdateNotificationService.new({ actor: current_user, action: "updated", resource: @company, resource_type: @company.class.name }).notify_admin
        flash[:alert] = "your update has been saved. but will only reflect on admins authorization"
        redirect_to company_url @company, tab: "company"
      end
    else
      @company.update(update_button: false)
      flash[:alert] = "no change in data"
      redirect_to company_url @company, tab: "company"
    end
  end
end

app/helpers/admin/companies_helper.rb
module Admin::CompaniesHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<div class="col-md-12">
	<div class="card">
		<div class="card-header" data-background-color="purple">
		<h4 class="title">Company Details</h4>
			<p class="category">Fill Out Details</p>
		</div>
		<div class="card-content">
			<%= simple_form_for([current_user, company]) do |f| %>
			<% if f.object.errors.any? %>
			<div class="alert alert-danger">  
				<% f.object.errors.full_messages.each do |msg| %>
				  <%= msg %>
				<br>
				<% end %>
			</div> 
			<% end %>
				<div class="row">
					<div class="col-md-3">
						<div class="form-group label-floating">
							<label class="control-label">Name Of Company</label>
							<%= f.input :company_name, maxlength: "30", label: false, class: "form-control" %>
						</div>
					</div>
					<div class="col-md-2">
						<div class="form-group label-floating">
							<label class="control-label">Industry</label>
							<%= f.association :industry, label: false, class: "form-control" %>
						</div>
					</div>
					<div class="col-md-4">
						<div class="form-group label-floating">
							<label class="control-label">Name Of Client</label>
							<%= f.input :clientname, maxlength: "30", label: false, class: "form-control" %> 
						</div>
					</div>
					<div class="col-md-2">
						<div class="form-group label-floating">
							<label class="control-label">Role/Job Title</label>
							<%= f.input :role, maxlength: "20", label: false, class: "form-control" %> 
						</div>
					</div>
				</div>

				<div class="row">
					<div class="col-md-3">
						<div class="form-group label-floating">
							<label class="control-label">Email</label>
							<%= f.input :email, maxlength: "30", label: false, class: "form-control" %>
						</div>
					</div>
					<div class="col-md-4">
						<div class="form-group label-floating">
							<label class="control-label">Phonenumber</label>
							<%= f.input :phonenumber, maxlength: "10", label: false, class: "form-control" %>
						</div>
					</div>
					<div class="col-md-4">
						<div class="form-group label-floating">
							<label class="control-label">url/website of company</label>
							<%= f.input :url, maxlength: "30", label: false, class: "form-control" %>
						</div>
					</div>
				</div>

				<div class="row">
					<div class="col-md-12">
						<div class="form-group">
							<label>Brief Description of Company</label>
							<div class="form-group label-floating">
								<label class="control-label"> Should include a brief description of what company does(in 500 characters or less)</label>
								<%= f.input :about, maxlength: "500", label: false, class: "form-control", rows: "5" %>
							</div>
						</div>
					</div>
				</div>
				<%= f.button :submit, class: "btn btn-primary btn-xs btn-round pull-right" %>
				<div class="clearfix"></div>
			<% end %>
		</div>
	</div>
</div>

app/views/companies/edit.html.erb
<%= render "form", company: @company %>

app/views/companies/index.html.erb
<%unless @companies.any? || @applicants.any? %>
  <h3>Your porfolio is empty</h3>
<% end %>
<%= link_to new_user_company_url(current_user) do %>
  <button class="btn btn-primary btn-xs btn-round">
    <% if @companies.any? %>
      <i class="material-icons">add</i>Add Another Company
    <% else %>
      <i class="material-icons">add</i>Add Company  
    <% end %>	
  </button>
<% end %>  

<% if @companies.any? %>
<div class="col-md-12">
	<div class="card">
		<div class="card-header" data-background-color="purple">
			<h4 class="title">Companies</h4>
			<p class="category">details of each company</p>
		</div>
		<div class="card-content table-responsive">
			<table class="table">
				<thead class="text-primary">
					<th>Name Of Company</th>
					<th>ClientName</th>
					<th>Role</th>
					<th>Email</th>
					<th>Phonenumber</th>
					<th>Url/Website</th>
					<th>Description</th>
					<th></th>
				</thead>
				<% @companies.each do |company| %>
				<tbody>
					
					<tr>
						<td>
						  <%= link_to user_company_url(current_user, company, tab: "company") do %>
						    <button class="btn btn-primary btn-xs btn-round">
						      <%= company.company_name %>	
						    </button>
						  <% end %>
						</td>
						<td><%= company.clientname %></td>
						<td><%= company.role %></td>
						<td><%= company.email %></td>
						<td><%= company.phonenumber %></td>
						<td class="text-primary"><%= company.url %></td>
						<td><%= truncate(company.about, length: 15) %></td>
						<td class="td-actions text-right">
							<%= link_to update_button_for_company_url(company), method: :patch do %>
							 <button type="button" title="Edit Task" class="btn btn-primary btn-simple btn-xs">
								<i class="material-icons">edit</i>
							</button>
							<% end %>
							<%= link_to user_company_url(current_user, company), method: :delete, data: { confirm: "Are you sure?" } do %>
						    <button type="button" title="Remove" class="btn btn-danger btn-simple btn-xs">
								<i class="material-icons">close</i>
							</button>
							<% end %>
						</td>  	
					</tr>
				</tbody>
				<% end %>
			</table>

		</div>
	</div>
</div>
<% end %>

<% if current_user.applicants.any? %>
<div class="col-md-12">
	<div class="card">
		<div class="card-header" data-background-color="purple">
			<h4 class="title">	
				Applicants and the roles they applied for
			</h4>
			<p class="category"></p>
		</div>
		<div class="card-content table-responsive">
			<table>
				<tbody>
					<% if @applicants.any? %>
					<% @count = 0 %>
					<% @applicants.each do |applicant| %>
					<% @count +=1 %>
					<tr>
						<td class="col-md-1"><%= @count %>.</td>
						<td class="col-md-4">
						<% if !applicant.job_description.nil? %> 
						  <%= link_to [applicant.job_description, applicant] do %>
						    <button class="btn btn-primary btn-xs btn-round">
						      <%= applicant.name %>	
						    </button>
						  <% end %>
						<% else %>
						<button class="btn btn-primary btn-xs btn-round">
						  <%= applicant.name %>	
						</button>
						  
						<% end %> 	
						 </td>
						<td class="col-md-2">applied for</td>
						<td class="col-md-4">
						<% if !applicant.job_description.nil? %>
						  <%= link_to [applicant.company, applicant.job_description] do %>
						  <button class="btn btn-primary btn-xs btn-round">
						  	<%= applicant.job_description.try(:job_title) %>
						  </button>
						  <% end %>
						<% else %>
						  -
						<% end %>	
						</td>
						<td>
							<% if applicant.none? %>
							<button class="btn btn-default btn-xs btn-round">
								no status
							</button>	
							<% elsif applicant.interviewing? %>
							<button class="btn btn-info btn-xs btn-round">
								interviewing...
							</button>	
							<% elsif applicant.testing? %>
							<button class="btn btn-info btn-xs btn-round">
								testing...
							</button>	
							<% elsif applicant.salary_negotiation? %>
							<button class="btn btn-warning btn-xs btn-round">
							  negotiation salary...
							</button>
							<% elsif applicant.hired? %>
							<button class="btn btn-success btn-xs btn-round">
								hired!
							</button>
							<% elsif applicant.not_hired? %>
							<button class="btn btn-danger btn-xs btn-round">
								not hired
							</button>	  	     
							<% end %>
						</td>
						<td>
						  <% if !applicant.job_description.nil? %>
						  <%= link_to update_button_for_applicants_url(applicant), method: :patch do %>
							<button type="button" title="Edit Task" class="btn btn-primary btn-simple btn-xs">
								<i class="material-icons">edit</i>
							</button>
					      <% end %>	
					      <% end %>
						</td>
						<td>
						  <% if applicant.job_description.nil? %>
						    <%= link_to job_description_applicant_url(applicant.job_description, applicant), method: :delete, data: {confirm: "are you sure you want to delete this applicant?"} do  %>
							  <button type="button" title="Remove" class="btn btn-primary btn-simple btn-xs">
							    <i class="material-icons">close</i>
							  </button>  	
						    <% end %>	
						  <% else %>
						  <% end %>
						</td>
					</tr>                                       
					<% end %>
					<% else %>
					<tr>
						<td class="col-md-4">no</td>
						<td class="col-md-2">data</td>
						<td class="col-md-4">here</td>						
					</tr>   
					<% end %> 
				</tbody>
			</table>
		</div>
	</div>
</div>
<% end %>