config/routes.rb
Rails.application.routes.draw do

  get 'bug_report/show'

  namespace :admin do
  get 'bug_reports/index'
  end

  namespace :admin do 
    get 'dashboard/dashboard', to: 'dashboard#dashboard', as: :dashboard
    # get 'dashboard/activity_feed', to: 'dashboard#activity_feed', as: :activity_feed
    patch 'companies/:id/update_button', to: 'companies#update_button', as: :update_button_for_company
    patch 'companies/:id/contact_company', to: 'companies#contact_company', as: :contact_company
    patch 'companies/:id/allow_changes_to_company', to: 'companies#allow_changes_to_company', as: :allow_changes_to_company
    patch 'companies/:id/deal_with_company', to: 'companies#deal_with_company', as: :deal_with_company

    patch 'job_descriptions/:id/update_button', to: 'job_descriptions#update_button', as: :update_button_for_jd
    patch 'job_descriptions/:id/allow_changes_to_jd', to: 'job_descriptions#allow_changes_to_jd', as: :allow_changes_to_jd
    patch 'applicants/:id/allow_changes_to_applicant', to: 'applicants#allow_changes_to_applicant', as: :allow_changes_to_applicant

    patch 'qualifications/:id/allow_changes_to_qualification', to: 'qualifications#allow_changes_to_qualification', as: :allow_changes_to_qualification
    patch 'required_experiences/:id/allow_changes_to_req_exp', to: 'required_experiences#allow_changes_to_req_exp', as: :allow_changes_to_req_exp
    patch 'requirements/:id/allow_changes_to_requirement', to: 'requirements#allow_changes_to_requirement', as: :allow_changes_to_requirement

    patch 'admin_users/:id/update_button', to: 'admin_users#update_button', as: :update_button_for_admin
    get 'activity_feed/index', to: 'activity_feed#index', as: :activity_feed
    get 'activity_feed/show', to: 'activity_feed#show', as: :show_activity
    patch 'messages/:id/send_message', to: 'messages#send_message', as: :send_message
    patch  'messages/:id/archive_message', to: 'messages#archive_message', as: :archive_message
    patch  'messages/:id/unarchive_message', to: 'messages#unarchive_message', as: :unarchive_message
    patch 'applicants/:id/update_salary', to: 'applicants#update_salary', as: :update_salary
    patch 'applicants/:id/update_button', to: 'applicants#update_button', as: :update_button_for_applicants
    get 'applicants/all_applicants', to: 'applicants#all_applicants', as: :manage_all_applicants
    patch 'users/:id/approve', to: 'users#approve', as: :approve_user
    patch 'users/:id/disapprove', to: 'users#disapprove', as: :disapprove_user
    patch 'applicants/:id/shortlist', to: 'applicants#shortlist', as: :shortlist_applicant
    patch 'applicants/:id/interviewing', to: 'applicants#interviewing', as: :interviewing_applicant
    patch 'applicants/:id/testing', to: 'applicants#testing', as: :testing_applicant
    patch 'applicants/:id/salary_negotiation', to: 'applicants#salary_negotiation', as: :negotiating_applicant_salary
    patch 'applicants/:id/hire', to: 'applicants#hire', as: :hire_applicant
    patch 'applicants/:id/unhire', to: 'applicants#unhire', as: :unhire_applicant
    get 'users/reset_cumulative_earnings', to: 'users#reset_cumulative_earnings', as: :reset_cumulative_earnings
    get 'notifications/:id/mark_as_read', to: 'notifications#mark_as_read', as: :mark_notification_as_read
    get 'notifications/mark_all_as_read', to: 'notifications#mark_all_as_read', as: :mark_all_as_read
    get 'notifications/mark_all_as_seen', to: 'notifications#mark_all_as_seen', as: :mark_all_as_seen
    get 'roles/set_role', to: 'roles#set_role', as: :set_role
    get 'roles/unset_role', to: 'roles#unset_role', as: :unset_role

    
    # scope module: "admin" do 
    #   resources :messages do 
    #     member do 
    #       patch 'read_by_admin_at'
    #     end
    #   end
    # end

    
    # resources :users, only: [] do 
    #   resources :companies
    # end
    resources :admin_users
    resources :users, only: [:index, :show]
    
    resources :companies do 
      resources :job_descriptions
    end

    resources :job_descriptions, only: [:index] do 
      resources :requirements, only: [:index, :show]
      resources :applicants
    end

    resources :messages

    resources :applicants, only: [] do 
      resources :comments
    end

    resources :activity_logs, only: [:index, :show]
    resources :bug_reports, only: [:index, :show]
  end

  devise_for :users, controllers: { registrations: :registrations, confirmations: :confirmations }

  root to: 'dashboard#index'
  # get 'dashboard/activity_feed', to: 'dashboard#activity_feed', as: :activity_feed
  
  patch 'companies/:id/update_button', to: 'companies#update_button', as: :update_button_for_company
  patch 'job_descriptions/:id/update_button', to: 'job_descriptions#update_button', as: :update_button_for_jd
  patch 'applicants/:id/update_button', to: 'applicants#update_button', as: :update_button_for_applicants
  patch 'requirements/:id/update_button', to: 'requirements#update_button', as: :update_button_for_rq
  patch 'qualifications/:id/update_button', to: 'qualifications#update_button', as: :update_button_for_qualification
  patch 'required_experiences/:id/update_button', to: 'required_experiences#update_button', as: :update_button_for_exp
  patch 'job_descriptions/:id/complete_job_description', to: 'job_descriptions#complete_job_description', as: :complete_jd
  patch 'job_descriptions/:id/update_job_description', to: 'job_descriptions#update_job_description', as: :update_jd
  get 'activity_feed/index', to: 'activity_feed#index', as: :activity_feed
  get 'activity_feed/show', to: 'activity_feed#show', as: :show_activity
  patch 'messages/:id/send_message', to: 'messages#send_message', as: :send_message
  patch  'messages/:id/archive_message', to: 'messages#archive_message', as: :archive_message
  patch  'messages/:id/unarchive_message', to: 'messages#unarchive_message', as: :unarchive_message
  get 'user_stats/statistics', to: 'user_stats#statistics', as: :user_stats
  patch 'users/edit_user_profile', to: 'users#edit_user_profile', as: :edit_user_profile
  patch 'bank_accounts/:id/edit_bank_details', to: 'bank_accounts#edit_bank_details', as: :edit_bank_details
  patch 'users/:id/complete_profile', to: 'users#complete_profile', as: :complete_profile
  patch 'users/:id/update_profile', to: 'users#update_profile', as: :update_profile
  get 'notifications/:id/mark_as_read', to: 'notifications#mark_as_read', as: :mark_notification_as_read
  get 'notifications/mark_all_as_read', to: 'notifications#mark_all_as_read', as: :mark_all_as_read
  get 'notifications/mark_all_as_seen', to: 'notifications#mark_all_as_seen', as: :mark_all_as_seen
  
  patch 'messages/:id/read_by_user', to: 'messages#read_by_user', as: :read_by_user


  resources :user, only: [] do 
    resources :companies, :bank_accounts 
  end

  resources :companies do 
    resources :job_descriptions
  end

  resources :job_descriptions, only: [] do 
    resources :requirements, :applicants, :qualifications, :required_experiences
  end

  resources :messages
  resources :applicants, only: [] do 
    resources :requirement_scores
  end

  resources :attachments, only: [:new, :show, :destroy] 

  match "*path", to: "application#routing_error", via: :all if Rails.env.production?
end

app/controllers/admin/job_descriptions_controller.rb
class Admin::JobDescriptionsController < Admin::ApplicationController
  before_action :set_admin_authorization_parameters, only: [:update_button, :update, :destroy, :allow_changes_to_jd]
  before_action :set_company, except: [:update_button, :index, :allow_changes_to_jd]
  before_action :set_job_description, only: [:show, :edit, :update, :destroy]
  after_action :pay_users_of_applicants, only: [:update]
  layout "admin"

  def index
    @completed_roles = JobDescription.all.includes(:company).where(copy: false, completed: true).order(created_at: :asc)
    @uncompleted_roles = JobDescription.all.includes(:company).where(copy: false, completed: false).order(created_at: :asc)
  end

  def show
    @job_description_copy = if job_description_copy = JobDescription.find_by(copy: true, copy_id: @job_description.id)
                  job_description_copy
                end   
  end

  def edit
  end

  def update
  	if @job_description.update(job_params)
  	  @job_description.update(update_button: false, edit_user_id: nil)	
       
      # please Derek, you know better than not to refactor this piece of shit! 
      if !params[:job_description][:applicant_id].blank?
        if @job_description.potential_worth.to_f != 0.0 && @job_description.percent_worth.to_f != 0.0 && @job_description.vacancy_percent_worth.to_f != 0.0
  	      flash[:success] = "you successfully updated job description, #{(Applicant.find(params[:job_description][:applicant_id].to_i)).name} is hired!"
          if !params[:job_description][:applicant_id].blank?
            Applicant.find(params[:job_description][:applicant_id].to_i).update(status: "hired") 
            Applicant.find(params[:job_description][:applicant_id].to_i).pay_user_when_applicant_is_hired 
            track_activity Applicant.find(params[:job_description][:applicant_id].to_i), "hired", Applicant.find(params[:job_description][:applicant_id].to_i).user
            ApplicantStatusNotificationService.new({ recipient: Applicant.find(params[:job_description][:applicant_id].to_i).user, actor: current_user, action: Applicant.find(params[:job_description][:applicant_id].to_i).status, resource: Applicant.find(params[:job_description][:applicant_id].to_i), resource_type: Applicant.find(params[:job_description][:applicant_id].to_i).class.name }).notify_user
          end
          @job_description.earning_algorithm
          if session[:track_user_path] == admin_job_description_applicant_url(@job_description, Applicant.find(params[:job_description][:applicant_id].to_i))
  	        redirect_to [:admin, @job_description, Applicant.find(params[:job_description][:applicant_id].to_i)]
          else
            redirect_to :back
          end
        else
          flash[:notice] = "you still have zero values for percent worth, potential worth and percent worth per vacancy for role: #{@job_description.job_title}"
          redirect_to :back
        end
      else
        if @job_description.potential_worth.to_f != 0.0 && @job_description.percent_worth.to_f != 0.0 && @job_description.vacancy_percent_worth.to_f != 0.0
          @job_description.earning_algorithm
          flash[:success] = "you successfully updated this job description"
          redirect_to :back
        else  
          flash[:notice] = "you still have zero values for percent worth, potential worth and percent worth per vacancy for role: #{@job_description.job_title}"
          redirect_to :back
        end
      end
  	else
  	  flash[:alert] = "oops! sthg went wrong"
  	  redirect_to :back
  	end
  end

  def destroy
    @job_description.destroy
    redirect_to :back
  end

  def update_button
  	@job_description = JobDescription.find(params[:id])
    if @job_description.company.contacted?
      if @job_description.updated? && @job_description.edit_user_id != current_user.id
        flash[:alert] = "can't proceed with this action. this jd is currently being worked on."
        redirect_to :back 
      else  
  	    @job_description.update(update_button: true, edit_user_id: current_user.id)
  	    redirect_to admin_company_url(@job_description.company, tab: "job descriptions") + "#job descriptions"
      end
    else
      flash[:alert] = "you must first contact the company with this job description"
      redirect_to admin_companies_url(company_id: @job_description.company.id)
    end
  end

  def allow_changes_to_jd
     @job_description_copy = if job_description_copy = JobDescription.find_by(copy: true, copy_id: @job_description.id)
                               job_description_copy
                             end   
     if @job_description_copy.attachments.any?
       if (@job_description.job_title != @job_description_copy.job_title) || (@job_description.experience != @job_description_copy.experience) || (@job_description.min_salary != 
         @job_description_copy.min_salary) || (@job_description.max_salary != @job_description_copy.max_salary) || (@job_description.vacancies != @job_description_copy.vacancies) || (@job_description.role_description != 
       @job_description_copy.role_description) || (@job_description.expiration_date != @job_description_copy.expiration_date) || (@job_description.attachments.first.file != @job_description_copy.attachments.first.file)

         job_description_copy_attributes = @job_description_copy.attributes 
         job_description_copy_attributes.delete("id")
         job_description_copy_attributes["copy"] = false 
         job_description_copy_attributes["copy_id"] = nil
         @job_description.update(job_description_copy_attributes)
         @job_description.attachments.first.update(file: @job_description_copy.attachments.first.file) 
         @job_description.update(completed: true)
         @job_description_copy.attachments.delete_all
         @job_description_copy.delete
         AuthorizeJobDescriptionUpdateNotificationService.new({ actor: current_user, action: "authorize", resource: @job_description, resource_type: @job_description.class.name }).notify_user
        flash[:success] = "changes have been incorporated."
      end
    else
      if (@job_description.job_title != @job_description_copy.job_title) || (@job_description.experience != @job_description_copy.experience) || (@job_description.min_salary != 
         @job_description_copy.min_salary) || (@job_description.max_salary != @job_description_copy.max_salary) || (@job_description.vacancies != @job_description_copy.vacancies) || (@job_description.role_description != 
       @job_description_copy.role_description) || (@job_description.expiration_date != @job_description_copy.expiration_date) 

         job_description_copy_attributes = @job_description_copy.attributes 
         job_description_copy_attributes.delete("id")
         job_description_copy_attributes["copy"] = false 
         job_description_copy_attributes["copy_id"] = nil
         @job_description.update(job_description_copy_attributes)
         @job_description.update(completed: true)
         @job_description_copy.attachments.delete_all
         @job_description_copy.delete
         AuthorizeJobDescriptionUpdateNotificationService.new({ actor: current_user, action: "authorize", resource: @job_description, resource_type: @job_description.class.name }).notify_user
        flash[:success] = "changes have been incorporated."
      end
    end
    redirect_to :back
  end


  private

  def set_company
  	@company = Company.find(params[:company_id])
  end

  def set_job_description
  	set_company
  	@job_description = @company.job_descriptions.find(params[:id])
  end

  def job_params
  	params.require(:job_description).permit(:job_title, :experience, :min_salary, :max_salary, :vacancies, :update_button, :potential_worth, :actual_worth, :percent_worth, :applicant_worth,
     :applicant_percent_worth, :earnings, :vacancy_worth, :vacancy_percent_worth, :edit_user_id)
  end

  def set_admin_authorization_parameters
    @job_description = JobDescription.find(params[:id])
    Authorization::AdminAuthorizationPolicy.new(current_user, @job_description, @job_description.class.name, self).implement_authorization_policy
  end

  def pay_users_of_applicants
    @job_description.applicants.each do |applicant|
      ApplicantStatusNotificationService.new({ recipient: applicant.user, actor: current_user, action: applicant.status, resource: applicant, resource_type: applicant.class.name }).notify_user
    end
  end
end

app/helpers/admin/job_descriptions_helper.rb
module Admin::JobDescriptionsHelper
end

app/helpers/job_descriptions_helper.rb
module JobDescriptionsHelper
end

app/views/admin/job_descriptions/show.html.erb
<div class="card-content table-responsive">
<div class="col-md-8">
	<div class="card">
		<div class="card-header" data-background-color="purple">
			<h4 class="title">Job Description For <%= @company.company_name %></h4>
		</div>
		<div class="card-content">
		<div>	
		<% if @job_description.completed? %>
		     <button class="btn btn-info btn-xs btn-round pull-right">
		     	completed
		     </button>
		<% else %>
		     <button class="btn btn-default btn-xs btn-round pull-right">
		     	not completed
		     </button> 
        <% end %>
        <button class="btn btn-success btn-xs btn-round pull-right">
          worth: GHS<%= @job_description.actual_worth || "0.00" %>	
        </button>	
        </div>
        <br>
        
        <% authorize? @job_description do %>
        <% pending_updates? @job_description do %>
        <div class="pull-right">
        	<button style="margin-right: -90px;margin-top: 20px;" type="button" class="btn btn-info btn-xs btn-round" data-toggle="modal" data-target="#myModal"><i class="material-icons">visibility</i>changes</button> 	
        </div> 
        <% end %>
        <% end %>  

        <!-- modal here -->
										<div id="myModal" class="modal fade" role="dialog">
											<div class="modal-dialog">

												<!-- Modal content-->
												<div class="modal-content">
													<div class="modal-header">
														<button type="button" class="close" data-dismiss="modal">&times;</button>
														<h4 class="modal-title">Changes</h4>
													</div>
													<div class="modal-body">
													<% if !@job_description_copy.nil? %>
													<% pending_updates? @job_description do %>
														<p>job title: <%= @job_description.job_title != @job_description_copy.job_title ? "#{@job_description_copy.job_title}**" : "#{@job_description.job_title}" %></p>
														<p>experience: <%= @job_description.experience != @job_description_copy.experience ? "#{@job_description_copy.experience}**" : "#{@job_description.experience}" %></p>
														<p>min salary: <%= @job_description.min_salary != @job_description_copy.min_salary ? "#{@job_description_copy.min_salary }**" : "#{@job_description.min_salary }" %></p>
														<p>max salary: <%= @job_description.max_salary != @job_description_copy.max_salary  ? "#{@job_description_copy.max_salary }**" : "#{@job_description.max_salary }" %></p>
														<p>vacancies: <%= @job_description.vacancies != @job_description_copy.vacancies ? "#{@job_description_copy.vacancies}**" : "#{@job_description.vacancies}" %></p>
														<p>role description: <%= @job_description.role_description != @job_description_copy.role_description ? "#{@job_description_copy.role_description}**" : "#{@job_description.role_description}" %></p>
														<p>expiration date: <%= @job_description.expiration_date != @job_description_copy.expiration_date ? "#{@job_description_copy.expiration_date}**" : "#{@job_description.expiration_date}" %></p>
														<p>uploads: <% @job_description_copy.attachments.each do |attachment| %>
						                                              <%= link_to File.basename(attachment.file.url), attachment.file.url %>(<%= number_to_human_size(attachment.file.size) %>)
						                                              <br>
						                                            <% end %>.</p>
						                            <% end %>                
													</div>
													<div class="modal-footer">
													  <%= link_to admin_allow_changes_to_jd_url(@job_description), method: :patch do %>
														<button type="button" class="btn btn-default btn-xs btn-round" data-dismiss="modal">Allow Changes</button>
													  <% end %>	
													  <% end %>
													</div>
												</div>

											</div>
										</div>
										<!-- modal ends here -->

		<span class="text-primary">Brief Description</span>
			<div class="row">
				<div class="col-md-4">
					<div class="form-group label-floating">
						<label class="control-label">Job Title</label>
						  <button class="btn btn-primary btn-xs btn-round">
						    <%= @job_description.job_title %>	
						  </button>
					</div>
				</div>
				<div class="col-md-2">
					<div class="form-group label-floating">
						<label class="control-label">Experience(yrs)</label>
						<%= @job_description.experience %> 
					</div>
				</div>
			</div>

			<div class="row">
				<div class="col-md-4">
					<div class="form-group label-floating">
						<label class="control-label">Minimum Salary</label>
						<%= @job_description.min_salary %>
					</div>
				</div>
				<div class="col-md-3">
					<div class="form-group label-floating">
						<label class="control-label">Maximum Salary</label>
						<%= @job_description.max_salary %>
					</div>
				</div>
			</div>

			<div class="row">
				<div class="col-md-4">
					<div class="form-group label-floating">
						<label class="control-label">Vacancies</label>
						<%= @job_description.vacancies %>
					</div>
				</div>
			</div>

			<div class="row">
			  <div class="col-md-12">
			    <div class="form-group label-floating">
			      <label class="control-label">role description</label>
			    	<%= @job_description.role_description %>
			    </div>	
			  </div>	
			</div>

			<div class="row">
				<div class="col-md-4">
					<div class="form-group label-floating">
						<label class="control-label">Document containing JD</label>
						<% if @job_description.attachments.any? { |attachment| attachment.persisted? } %>
						<% @job_description.attachments.each do |attachment| %>
						  <%= link_to File.basename(attachment.file.url), attachment.file.url %>(<%= number_to_human_size(attachment.file.size) %>)
						  <br>
						<% end %>
						<% else %>
						  No file uploaded.
						<% end %>
					</div>
				</div>
			</div>

			<div class="row">
			  <div class="col-md-12">
			    <div class="form-group label-floating">
			      <label class="control-label">expiration date</label>
			      <%= @job_description.expiration_date.strftime("%B %d, %Y @%r") %>	
			    </div>	
			  </div>	
			</div>

			<br/>
			<br/>
			<hr>


	
			  <div class="row">
				  <div class="col-md-12">
				    <div class="form-group label-floating">
					  <span class="text-primary">Required Qualifications</span>
					    <% if @job_description.qualifications.any? %>
					       <table>
						  <% @job_description.qualifications.where(copy: false, copy_id: nil).each do |qualification| %>							    
								<tr>
								  <td class="col-md-1"><%= qualification.certificate %></td> <td class="col-md-1">in</td>
								  <td class="col-md-4"><%= qualification.field_of_study %></td> 
							    </tr>
						<br/>

						  <% end %>
						  </table>
						<% else %>
						<p>No Qualifications Provided</p>  
						<% end %>
					</div>
					<td>
					<% authorize? @job_description do %>
					  <% if @job_description.qualifications.where(copy: true).any? %>
						<div class="pull-right">
							<span class="dropdown">
								<button type="button" style="margin-top: -40px;" class="dropdown-toggle btn btn-info btn-xs btn-round" data-toggle="dropdown"><i class="material-icons">visibility</i>changes<i class="material-icons">keyboard_arrow_down</i></button>
								<ul class="dropdown-menu" class="col-md-8">
								<% @job_description.qualifications.where(copy: true).each do |qualification| %>  
								  <li style="width: 350px;"><%= qualification.certificate %> in <%= qualification.field_of_study %><br/>
								  <% authorize? qualification do %>
								    <%= link_to "allow changes", admin_allow_changes_to_qualification_url(Qualification.find(qualification.copy_id)), method: :patch, class: "btn btn-default btn-xs btn-round" %>	
								  <% end %>
								  </li>								  
								<% end %>  
								</ul> 
							</span>	
						</div>
					  <% end %>	 
					  <% end %>
					</td>
				</div>
			</div>

			<br/>
			<br/>
			<hr>


			<div class="row">
			  <div class="col-md-12">
			    <div class="form-group label-floating">
				  <span class="text-primary">Required Experiences</span>
				    <% if @job_description.required_experiences.any? %>
				    <table>
					  <% @job_description.required_experiences.where(copy: false, copy_id: nil).each do |required_experience| %>		
						  <tr>
						    <td class="col-md-2"><%= required_experience.years %> years</td><td class="col-md-1">of</td><td class="col-md-4"><%= required_experience.experience %></td>  
						  </tr>
					      
					<br/>
					
					

					<% end %>
					</table>
					<% else %>
					<p>No Experience Provided</p> 
					<% end %>
				</div>
				<td>
				<% authorize? @job_description do %>
				  <% if @job_description.required_experiences.where(copy: true).any? %>
					<div class="pull-right">
						<span class="dropdown">
							<button type="button" style="margin-top: -40px;" class="dropdown-toggle btn btn-info btn-xs btn-round" data-toggle="dropdown"><i class="material-icons">visibility</i>changes<i class="material-icons">keyboard_arrow_down</i></button>
							<ul class="dropdown-menu">
								<% @job_description.required_experiences.where(copy: true).each do |required_experience| %>  
								  <li style="width: 350px;"><%= required_experience.years %> years</td><td class="col-md-1">of</td><td class="col-md-4"><%= required_experience.experience %><br/>
								  <% authorize? required_experience do %>	
								    <%= link_to "allow changes", admin_allow_changes_to_req_exp_url(RequiredExperience.find(required_experience.copy_id)), method: :patch, class: "btn btn-default btn-xs btn-round" %></li>
								  <% end %>	
								<% end %>  
							</ul> 
						</span>	
					</div> 
				  <% end %>	
				  <% end %>
				</td>
			</div>
		</div>

	    <br/>
		<br/>
		<hr>

	    <div class="row">
			  <div class="col-md-12">
			    <div class="form-group label-floating">
				  <span class="text-primary">Compulsory Requirements</span>
				    <% if @job_description.requirements.any? %>
				    <table>
					  <% @job_description.requirements.where(copy: false, copy_id: nil).each do |requirement| %>	    
						  <tr>
							<td class="col-md-4"><%= requirement.content %></td>  
						  </tr>
					      
					<br/>
					
					
					<% end %>
					</table>
					<% else %>
					<p>No Requirements Listed</p>
					<% end %>
				</div>
				<td>
				<% authorize? @job_description do %>
				  <% if @job_description.requirements.where(copy: true).any? %>
					<div class="pull-right">
						<span class="dropdown">
							<button type="button" style="margin-top: -40px;" class="dropdown-toggle btn btn-info btn-xs btn-round" data-toggle="dropdown"><i class="material-icons">visibility</i>changes<i class="material-icons">keyboard_arrow_down</i></button>
							<ul class="dropdown-menu">
								<% @job_description.requirements.where(copy: true).each do |requirement| %>  
								  <li style="width: 350px;"><%= requirement.content %><br/>
								  <% authorize? requirement do %>	
								    <%= link_to "Allow Changes", admin_allow_changes_to_requirement_url(Requirement.find(requirement.copy_id)), method: :patch, class: "btn btn-default btn-xs btn-round" %>
								<% end %>
								<% end %>  
							</ul> 
						</span>	
					</div> 
				  <% end %>	
				  <% end %>
				</td>
			</div>
		</div>


	    <div class="row">
		  <%= link_to "Back", :back, class: "btn btn-primary btn-xs btn-round pull-right" %>
	    </div>

	</div>



</div>
</div>
</div>


<%= javascript_include_tag "admin/jquery-3.1.0.min" %>
<%= javascript_include_tag "admin/bootstrap.min" %>
<%= javascript_include_tag "admin/material.min" %>
<%= javascript_include_tag "admin/chartist.min" %>
<%= javascript_include_tag "admin/bootstrap-notify" %>
<%= javascript_include_tag "admin/material-dashboard" %>